project_id = "xnhtlotbmdteubpwowds"

[functions.send-24hr-reminders]
verify_jwt = false

[functions.send-2hr-reminders]
verify_jwt = false

[functions.wati-webhook]
verify_jwt = false

[functions.process-booking-message]
verify_jwt = false
